// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VY.MenuActions.Infraestructure.Impl.Context;

namespace VY.MenuActions.Infraestructure.Impl.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    partial class MenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("VY.MenuActions.Infraestructure.Contracts.Entities.MenuAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportsTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportsTo");

                    b.ToTable("MenuAction");
                });

            modelBuilder.Entity("VY.MenuActions.Infraestructure.Contracts.Entities.MenuAction", b =>
                {
                    b.HasOne("VY.MenuActions.Infraestructure.Contracts.Entities.MenuAction", "ReportsToNavigation")
                        .WithMany("InverseReportsToNavigation")
                        .HasForeignKey("ReportsTo")
                        .HasConstraintName("FK_MenuActions_MenuActions")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReportsToNavigation");
                });

            modelBuilder.Entity("VY.MenuActions.Infraestructure.Contracts.Entities.MenuAction", b =>
                {
                    b.Navigation("InverseReportsToNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
